"""
Locked Zesimo fulfillment map (phases 1–5).

provider = "zesimo"
provider_sku = package_id (portal /packages/{id}/order)
Prefer cheap-ladder IDs only.

Everything NOT listed here keeps existing rules:
  - Saudi fixed 3/5/10/20/50 → esimaccess
  - Saudi unlimited 1d / 14d → esimaccess (day-pass / no twin in this cut)
  - Caribbean regional → telna
  - Africa regional → telna
  - Remaining ME silent (israel/tunisia/cyprus) → telna
  - PAYG → citrus
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

ZESIMO_SKU_MAP: List[Dict[str, Any]] = [
    {
        "phase": 5,
        "catalog_key": "me-1gb-7",
        "country_code": None,
        "country_slug": "regional-middle-east",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1083",
        "provider_slug": "zesimo-me-1gb-7d",
        "wholesale_cents": 233,
        "retail_cents": 599,
        "product_name": "MIDDLE EAST 1GB 7 Days",
    },
    {
        "phase": 1,
        "catalog_key": "sa-unlimited-3gb-7d",
        "country_code": "SA",
        "country_slug": "saudi-arabia",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "10903",
        "provider_slug": "zesimo-sa-unlimited-7d",
        "wholesale_cents": 2142,
        "retail_cents": 3499,
        "product_name": "Saudi Arabia Unlimited 7 Days",
    },
    {
        "phase": 1,
        "catalog_key": "sa-unlimited-3gb-10d",
        "country_code": "SA",
        "country_slug": "saudi-arabia",
        "data_gb": 3.0,
        "validity_days": 10,
        "package_id": "10905",
        "provider_slug": "zesimo-sa-unlimited-10d",
        "wholesale_cents": 2786,
        "retail_cents": 4299,
        "product_name": "Saudi Arabia Unlimited 10 Days",
    },
    {
        "phase": 1,
        "catalog_key": "me-5gb-15",
        "country_code": None,
        "country_slug": "regional-middle-east",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "1085",
        "provider_slug": "zesimo-me-5gb-15d",
        "wholesale_cents": 991,
        "retail_cents": 1999,
        "product_name": "MIDDLE EAST 5GB 15 Days",
    },
    {
        "phase": 1,
        "catalog_key": "me-10gb-30",
        "country_code": None,
        "country_slug": "regional-middle-east",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1086",
        "provider_slug": "zesimo-me-10gb-30d",
        "wholesale_cents": 1784,
        "retail_cents": 3299,
        "product_name": "MIDDLE EAST 10GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "eu-5gb-30",
        "country_code": None,
        "country_slug": "regional-europe",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "11707",
        "provider_slug": "zesimo-eu-5gb-30d",
        "wholesale_cents": 602,
        "retail_cents": 1799,
        "product_name": "Europe 5GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "eu-10gb-30",
        "country_code": None,
        "country_slug": "regional-europe",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "11709",
        "provider_slug": "zesimo-eu-10gb-30d",
        "wholesale_cents": 966,
        "retail_cents": 2299,
        "product_name": "Europe 10GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "la-5gb-30",
        "country_code": None,
        "country_slug": "regional-south-america",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "12121",
        "provider_slug": "zesimo-la-5gb-30d",
        "wholesale_cents": 1050,
        "retail_cents": 2299,
        "product_name": "Latin America 5GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "la-10gb-30",
        "country_code": None,
        "country_slug": "regional-south-america",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "12122",
        "provider_slug": "zesimo-la-10gb-30d",
        "wholesale_cents": 1764,
        "retail_cents": 3499,
        "product_name": "Latin America 10GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "mx-5gb-30",
        "country_code": "MX",
        "country_slug": "mexico",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "8186",
        "provider_slug": "zesimo-mx-5gb-30d",
        "wholesale_cents": 812,
        "retail_cents": 1799,
        "product_name": "Mexico 5GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "mx-10gb-30",
        "country_code": "MX",
        "country_slug": "mexico",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "8188",
        "provider_slug": "zesimo-mx-10gb-30d",
        "wholesale_cents": 1400,
        "retail_cents": 2799,
        "product_name": "Mexico 10GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "us-5gb-30",
        "country_code": "US",
        "country_slug": "united-states",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "3363",
        "provider_slug": "zesimo-us-5gb-30d",
        "wholesale_cents": 463,
        "retail_cents": 1499,
        "product_name": "United States 5GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "us-10gb-30",
        "country_code": "US",
        "country_slug": "united-states",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "7673",
        "provider_slug": "zesimo-us-10gb-30d",
        "wholesale_cents": 809,
        "retail_cents": 1999,
        "product_name": "United States 10GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "na-10gb-30",
        "country_code": None,
        "country_slug": "regional-north-america",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "587",
        "provider_slug": "zesimo-na-10gb-30d",
        "wholesale_cents": 1403,
        "retail_cents": 2799,
        "product_name": "North America 10GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "as-5gb-30",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "11733",
        "provider_slug": "zesimo-as-5gb-30d",
        "wholesale_cents": 434,
        "retail_cents": 1799,
        "product_name": "Asia 5GB 30 Days",
    },
    {
        "phase": 2,
        "catalog_key": "as-10gb-30",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "11736",
        "provider_slug": "zesimo-as-10gb-30d",
        "wholesale_cents": 714,
        "retail_cents": 2999,
        "product_name": "Asia 10GB 30 Days",
    },
    {
        "phase": 3,
        "catalog_key": "eu-20gb-30",
        "country_code": None,
        "country_slug": "regional-europe",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "11711",
        "provider_slug": "zesimo-eu-20gb-30d",
        "wholesale_cents": 1526,
        "retail_cents": 3999,
        "product_name": "Europe 20GB 30 Days",
    },
    {
        "phase": 3,
        "catalog_key": "as-20gb-30",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "11738",
        "provider_slug": "zesimo-as-20gb-30d",
        "wholesale_cents": 1092,
        "retail_cents": 3999,
        "product_name": "Asia 20GB 30 Days",
    },
    {
        "phase": 3,
        "catalog_key": "us-20gb-30",
        "country_code": "US",
        "country_slug": "united-states",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "7677",
        "provider_slug": "zesimo-us-20gb-30d",
        "wholesale_cents": 1450,
        "retail_cents": 2999,
        "product_name": "United States 20GB 30 Days",
    },
    {
        "phase": 3,
        "catalog_key": "la-20gb-30",
        "country_code": None,
        "country_slug": "regional-south-america",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "12123",
        "provider_slug": "zesimo-la-20gb-30d",
        "wholesale_cents": 2814,
        "retail_cents": 4999,
        "product_name": "Latin America 20GB 30 Days",
    },
    {
        "phase": 3,
        "catalog_key": "mx-20gb-30",
        "country_code": "MX",
        "country_slug": "mexico",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8190",
        "provider_slug": "zesimo-mx-20gb-30d",
        "wholesale_cents": 2226,
        "retail_cents": 3999,
        "product_name": "Mexico 20GB 30 Days",
    },
    {
        "phase": 3,
        "catalog_key": "eu-1gb-7",
        "country_code": None,
        "country_slug": "regional-europe",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "11701",
        "provider_slug": "zesimo-eu-1gb-7d",
        "wholesale_cents": 252,
        "retail_cents": 999,
        "product_name": "Europe 1GB 7 Days",
    },
    {
        "phase": 3,
        "catalog_key": "na-1gb-7",
        "country_code": None,
        "country_slug": "regional-north-america",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "580",
        "provider_slug": "zesimo-na-1gb-7d",
        "wholesale_cents": 182,
        "retail_cents": 799,
        "product_name": "North America 1GB 7 Days",
    },
    {
        "phase": 3,
        "catalog_key": "gulf-5gb-30",
        "country_code": None,
        "country_slug": "regional-gulf",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "2544",
        "provider_slug": "zesimo-gulf-5gb-30d",
        "wholesale_cents": 1512,
        "retail_cents": 2799,
        "product_name": "Gulf Region 5GB 30 Days",
    },
    {
        "phase": 3,
        "catalog_key": "la-3gb-30",
        "country_code": None,
        "country_slug": "regional-south-america",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "12094",
        "provider_slug": "zesimo-la-3gb-30d",
        "wholesale_cents": 700,
        "retail_cents": 1699,
        "product_name": "Latin America 3GB 30 Days",
    },
    {
        "phase": 4,
        "catalog_key": "gl-1gb-5",
        "country_code": None,
        "country_slug": "regional-global",
        "data_gb": 1.0,
        "validity_days": 5,
        "package_id": "11818",
        "provider_slug": "zesimo-global-1gb-5d",
        "wholesale_cents": 350,
        "retail_cents": 999,
        "product_name": "Global 1GB 5 Days",
    },
    {
        "phase": 4,
        "catalog_key": "gl-3gb-30",
        "country_code": None,
        "country_slug": "regional-global",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "11804",
        "provider_slug": "zesimo-global-3gb-30d",
        "wholesale_cents": 938,
        "retail_cents": 2499,
        "product_name": "Global 3GB 30 Days",
    },
    {
        "phase": 4,
        "catalog_key": "gl-5gb-30",
        "country_code": None,
        "country_slug": "regional-global",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "11806",
        "provider_slug": "zesimo-global-5gb-30d",
        "wholesale_cents": 1470,
        "retail_cents": 3499,
        "product_name": "Global 5GB 30 Days",
    },
    {
        "phase": 4,
        "catalog_key": "gl-10gb-30",
        "country_code": None,
        "country_slug": "regional-global",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "11808",
        "provider_slug": "zesimo-global-10gb-30d",
        "wholesale_cents": 2520,
        "retail_cents": 4999,
        "product_name": "Global 10GB 30 Days",
    },
    {
        "phase": 4,
        "catalog_key": "na-3gb-30",
        "country_code": None,
        "country_slug": "regional-north-america",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "2290",
        "provider_slug": "zesimo-na-3gb-30d",
        "wholesale_cents": 785,
        "retail_cents": 1799,
        "product_name": "North America 3GB 30 Days",
    },
    {
        "phase": 4,
        "catalog_key": "na-5gb-30",
        "country_code": None,
        "country_slug": "regional-north-america",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "7063",
        "provider_slug": "zesimo-na-5gb-30d",
        "wholesale_cents": 1175,
        "retail_cents": 2299,
        "product_name": "North America 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "turkey-1gb-7",
        "country_code": "TR",
        "country_slug": "turkey",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1758",
        "provider_slug": "zesimo-turkey-1gb-7",
        "wholesale_cents": 64,
        "retail_cents": 199,
        "product_name": "Turkey 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "turkey-3gb-7",
        "country_code": "TR",
        "country_slug": "turkey",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "537",
        "provider_slug": "zesimo-turkey-3gb-7",
        "wholesale_cents": 220,
        "retail_cents": 599,
        "product_name": "Turkey 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "turkey-5gb-15",
        "country_code": "TR",
        "country_slug": "turkey",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "538",
        "provider_slug": "zesimo-turkey-5gb-15",
        "wholesale_cents": 349,
        "retail_cents": 899,
        "product_name": "Turkey 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "turkey-10gb-30",
        "country_code": "TR",
        "country_slug": "turkey",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1761",
        "provider_slug": "zesimo-turkey-10gb-30",
        "wholesale_cents": 449,
        "retail_cents": 1099,
        "product_name": "Turkey 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "turkey-20gb-30",
        "country_code": "TR",
        "country_slug": "turkey",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8083",
        "provider_slug": "zesimo-turkey-20gb-30",
        "wholesale_cents": 728,
        "retail_cents": 1799,
        "product_name": "Turkey 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uae-1gb-7",
        "country_code": "AE",
        "country_slug": "uae",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "2047",
        "provider_slug": "zesimo-uae-1gb-7",
        "wholesale_cents": 245,
        "retail_cents": 599,
        "product_name": "United Arab Emirates 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uae-3gb-7",
        "country_code": "AE",
        "country_slug": "uae",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "555",
        "provider_slug": "zesimo-uae-3gb-7",
        "wholesale_cents": 902,
        "retail_cents": 2199,
        "product_name": "United Arab Emirates 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uae-5gb-15",
        "country_code": "AE",
        "country_slug": "uae",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "556",
        "provider_slug": "zesimo-uae-5gb-15",
        "wholesale_cents": 1427,
        "retail_cents": 3399,
        "product_name": "United Arab Emirates 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uae-10gb-30",
        "country_code": "AE",
        "country_slug": "uae",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "8494",
        "provider_slug": "zesimo-uae-10gb-30",
        "wholesale_cents": 1596,
        "retail_cents": 3799,
        "product_name": "United Arab Emirates 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uae-20gb-30",
        "country_code": "AE",
        "country_slug": "uae",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8496",
        "provider_slug": "zesimo-uae-20gb-30",
        "wholesale_cents": 2520,
        "retail_cents": 5999,
        "product_name": "United Arab Emirates 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "egypt-1gb-7",
        "country_code": "EG",
        "country_slug": "egypt",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "152",
        "provider_slug": "zesimo-egypt-1gb-7",
        "wholesale_cents": 130,
        "retail_cents": 399,
        "product_name": "Egypt 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "egypt-3gb-7",
        "country_code": "EG",
        "country_slug": "egypt",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "153",
        "provider_slug": "zesimo-egypt-3gb-7",
        "wholesale_cents": 352,
        "retail_cents": 899,
        "product_name": "Egypt 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "egypt-5gb-15",
        "country_code": "EG",
        "country_slug": "egypt",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "154",
        "provider_slug": "zesimo-egypt-5gb-15",
        "wholesale_cents": 557,
        "retail_cents": 1399,
        "product_name": "Egypt 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "egypt-10gb-30",
        "country_code": "EG",
        "country_slug": "egypt",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "155",
        "provider_slug": "zesimo-egypt-10gb-30",
        "wholesale_cents": 1003,
        "retail_cents": 2399,
        "product_name": "Egypt 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "egypt-20gb-30",
        "country_code": "EG",
        "country_slug": "egypt",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "156",
        "provider_slug": "zesimo-egypt-20gb-30",
        "wholesale_cents": 1769,
        "retail_cents": 4199,
        "product_name": "Egypt 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "qatar-1gb-7",
        "country_code": "QA",
        "country_slug": "qatar",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "446",
        "provider_slug": "zesimo-qatar-1gb-7",
        "wholesale_cents": 155,
        "retail_cents": 399,
        "product_name": "Qatar 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "qatar-3gb-7",
        "country_code": "QA",
        "country_slug": "qatar",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "447",
        "provider_slug": "zesimo-qatar-3gb-7",
        "wholesale_cents": 419,
        "retail_cents": 999,
        "product_name": "Qatar 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "qatar-5gb-15",
        "country_code": "QA",
        "country_slug": "qatar",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "448",
        "provider_slug": "zesimo-qatar-5gb-15",
        "wholesale_cents": 661,
        "retail_cents": 1599,
        "product_name": "Qatar 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "qatar-10gb-30",
        "country_code": "QA",
        "country_slug": "qatar",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "10799",
        "provider_slug": "zesimo-qatar-10gb-30",
        "wholesale_cents": 1022,
        "retail_cents": 2499,
        "product_name": "Qatar 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "qatar-20gb-30",
        "country_code": "QA",
        "country_slug": "qatar",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "450",
        "provider_slug": "zesimo-qatar-20gb-30",
        "wholesale_cents": 2101,
        "retail_cents": 4999,
        "product_name": "Qatar 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "kuwait-1gb-7",
        "country_code": "KW",
        "country_slug": "kuwait",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "296",
        "provider_slug": "zesimo-kuwait-1gb-7",
        "wholesale_cents": 135,
        "retail_cents": 399,
        "product_name": "Kuwait 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "kuwait-3gb-7",
        "country_code": "KW",
        "country_slug": "kuwait",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "297",
        "provider_slug": "zesimo-kuwait-3gb-7",
        "wholesale_cents": 365,
        "retail_cents": 899,
        "product_name": "Kuwait 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "kuwait-5gb-15",
        "country_code": "KW",
        "country_slug": "kuwait",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "298",
        "provider_slug": "zesimo-kuwait-5gb-15",
        "wholesale_cents": 578,
        "retail_cents": 1399,
        "product_name": "Kuwait 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "kuwait-10gb-30",
        "country_code": "KW",
        "country_slug": "kuwait",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "299",
        "provider_slug": "zesimo-kuwait-10gb-30",
        "wholesale_cents": 1041,
        "retail_cents": 2499,
        "product_name": "Kuwait 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "kuwait-20gb-30",
        "country_code": "KW",
        "country_slug": "kuwait",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "300",
        "provider_slug": "zesimo-kuwait-20gb-30",
        "wholesale_cents": 1836,
        "retail_cents": 4399,
        "product_name": "Kuwait 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "bahrain-1gb-7",
        "country_code": "BH",
        "country_slug": "bahrain",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "56",
        "provider_slug": "zesimo-bahrain-1gb-7",
        "wholesale_cents": 179,
        "retail_cents": 499,
        "product_name": "Bahrain 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "bahrain-3gb-7",
        "country_code": "BH",
        "country_slug": "bahrain",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "57",
        "provider_slug": "zesimo-bahrain-3gb-7",
        "wholesale_cents": 484,
        "retail_cents": 1199,
        "product_name": "Bahrain 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "bahrain-5gb-15",
        "country_code": "BH",
        "country_slug": "bahrain",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "58",
        "provider_slug": "zesimo-bahrain-5gb-15",
        "wholesale_cents": 765,
        "retail_cents": 1799,
        "product_name": "Bahrain 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "bahrain-10gb-30",
        "country_code": "BH",
        "country_slug": "bahrain",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "59",
        "provider_slug": "zesimo-bahrain-10gb-30",
        "wholesale_cents": 1378,
        "retail_cents": 3299,
        "product_name": "Bahrain 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "bahrain-20gb-30",
        "country_code": "BH",
        "country_slug": "bahrain",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "60",
        "provider_slug": "zesimo-bahrain-20gb-30",
        "wholesale_cents": 2432,
        "retail_cents": 5799,
        "product_name": "Bahrain 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "oman-1gb-7",
        "country_code": "OM",
        "country_slug": "oman",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "750",
        "provider_slug": "zesimo-oman-1gb-7",
        "wholesale_cents": 182,
        "retail_cents": 499,
        "product_name": "Oman 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "oman-3gb-7",
        "country_code": "OM",
        "country_slug": "oman",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "751",
        "provider_slug": "zesimo-oman-3gb-7",
        "wholesale_cents": 492,
        "retail_cents": 1199,
        "product_name": "Oman 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "oman-5gb-15",
        "country_code": "OM",
        "country_slug": "oman",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "752",
        "provider_slug": "zesimo-oman-5gb-15",
        "wholesale_cents": 780,
        "retail_cents": 1899,
        "product_name": "Oman 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "oman-10gb-30",
        "country_code": "OM",
        "country_slug": "oman",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "753",
        "provider_slug": "zesimo-oman-10gb-30",
        "wholesale_cents": 1404,
        "retail_cents": 3299,
        "product_name": "Oman 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "oman-20gb-30",
        "country_code": "OM",
        "country_slug": "oman",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "754",
        "provider_slug": "zesimo-oman-20gb-30",
        "wholesale_cents": 2476,
        "retail_cents": 5899,
        "product_name": "Oman 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "morocco-1gb-7",
        "country_code": "MA",
        "country_slug": "morocco",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1887",
        "provider_slug": "zesimo-morocco-1gb-7",
        "wholesale_cents": 167,
        "retail_cents": 399,
        "product_name": "Morocco 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "morocco-3gb-7",
        "country_code": "MA",
        "country_slug": "morocco",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "357",
        "provider_slug": "zesimo-morocco-3gb-7",
        "wholesale_cents": 787,
        "retail_cents": 1899,
        "product_name": "Morocco 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "morocco-5gb-15",
        "country_code": "MA",
        "country_slug": "morocco",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "358",
        "provider_slug": "zesimo-morocco-5gb-15",
        "wholesale_cents": 1246,
        "retail_cents": 2999,
        "product_name": "Morocco 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "morocco-10gb-30",
        "country_code": "MA",
        "country_slug": "morocco",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "2563",
        "provider_slug": "zesimo-morocco-10gb-30",
        "wholesale_cents": 1219,
        "retail_cents": 2899,
        "product_name": "Morocco 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "morocco-20gb-30",
        "country_code": "MA",
        "country_slug": "morocco",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "2201",
        "provider_slug": "zesimo-morocco-20gb-30",
        "wholesale_cents": 2164,
        "retail_cents": 5099,
        "product_name": "Morocco 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "jordan-1gb-7",
        "country_code": "JO",
        "country_slug": "jordan",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1787",
        "provider_slug": "zesimo-jordan-1gb-7",
        "wholesale_cents": 260,
        "retail_cents": 699,
        "product_name": "Jordan 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "jordan-3gb-7",
        "country_code": "JO",
        "country_slug": "jordan",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "273",
        "provider_slug": "zesimo-jordan-3gb-7",
        "wholesale_cents": 1182,
        "retail_cents": 2799,
        "product_name": "Jordan 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "jordan-5gb-15",
        "country_code": "JO",
        "country_slug": "jordan",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "274",
        "provider_slug": "zesimo-jordan-5gb-15",
        "wholesale_cents": 1873,
        "retail_cents": 4499,
        "product_name": "Jordan 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "jordan-10gb-30",
        "country_code": "JO",
        "country_slug": "jordan",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "6567",
        "provider_slug": "zesimo-jordan-10gb-30",
        "wholesale_cents": 1845,
        "retail_cents": 4399,
        "product_name": "Jordan 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "jordan-20gb-30",
        "country_code": "JO",
        "country_slug": "jordan",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "6570",
        "provider_slug": "zesimo-jordan-20gb-30",
        "wholesale_cents": 3382,
        "retail_cents": 7999,
        "product_name": "Jordan 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uk-1gb-7",
        "country_code": "GB",
        "country_slug": "uk",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1725",
        "provider_slug": "zesimo-uk-1gb-7",
        "wholesale_cents": 80,
        "retail_cents": 199,
        "product_name": "United Kingdom 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uk-5gb-30",
        "country_code": "GB",
        "country_slug": "uk",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1611",
        "provider_slug": "zesimo-uk-5gb-30",
        "wholesale_cents": 333,
        "retail_cents": 799,
        "product_name": "United Kingdom 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uk-10gb-30",
        "country_code": "GB",
        "country_slug": "uk",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1727",
        "provider_slug": "zesimo-uk-10gb-30",
        "wholesale_cents": 599,
        "retail_cents": 1499,
        "product_name": "United Kingdom 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "uk-20gb-30",
        "country_code": "GB",
        "country_slug": "uk",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "11554",
        "provider_slug": "zesimo-uk-20gb-30",
        "wholesale_cents": 1008,
        "retail_cents": 2399,
        "product_name": "United Kingdom 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "spain-1gb-7",
        "country_code": "ES",
        "country_slug": "spain",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1717",
        "provider_slug": "zesimo-spain-1gb-7",
        "wholesale_cents": 80,
        "retail_cents": 199,
        "product_name": "Spain 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "spain-5gb-30",
        "country_code": "ES",
        "country_slug": "spain",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "11563",
        "provider_slug": "zesimo-spain-5gb-30",
        "wholesale_cents": 308,
        "retail_cents": 799,
        "product_name": "Spain 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "spain-10gb-30",
        "country_code": "ES",
        "country_slug": "spain",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "11565",
        "provider_slug": "zesimo-spain-10gb-30",
        "wholesale_cents": 462,
        "retail_cents": 1099,
        "product_name": "Spain 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "spain-20gb-30",
        "country_code": "ES",
        "country_slug": "spain",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "11567",
        "provider_slug": "zesimo-spain-20gb-30",
        "wholesale_cents": 686,
        "retail_cents": 1699,
        "product_name": "Spain 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "italy-1gb-7",
        "country_code": "IT",
        "country_slug": "italy",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1699",
        "provider_slug": "zesimo-italy-1gb-7",
        "wholesale_cents": 80,
        "retail_cents": 199,
        "product_name": "Italy 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "italy-5gb-30",
        "country_code": "IT",
        "country_slug": "italy",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "8055",
        "provider_slug": "zesimo-italy-5gb-30",
        "wholesale_cents": 322,
        "retail_cents": 799,
        "product_name": "Italy 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "italy-10gb-30",
        "country_code": "IT",
        "country_slug": "italy",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1701",
        "provider_slug": "zesimo-italy-10gb-30",
        "wholesale_cents": 599,
        "retail_cents": 1499,
        "product_name": "Italy 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "italy-20gb-30",
        "country_code": "IT",
        "country_slug": "italy",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8059",
        "provider_slug": "zesimo-italy-20gb-30",
        "wholesale_cents": 980,
        "retail_cents": 2399,
        "product_name": "Italy 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "germany-1gb-7",
        "country_code": "DE",
        "country_slug": "germany",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1644",
        "provider_slug": "zesimo-germany-1gb-7",
        "wholesale_cents": 80,
        "retail_cents": 199,
        "product_name": "Germany 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "germany-5gb-30",
        "country_code": "DE",
        "country_slug": "germany",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1593",
        "provider_slug": "zesimo-germany-5gb-30",
        "wholesale_cents": 333,
        "retail_cents": 799,
        "product_name": "Germany 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "germany-10gb-30",
        "country_code": "DE",
        "country_slug": "germany",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1646",
        "provider_slug": "zesimo-germany-10gb-30",
        "wholesale_cents": 599,
        "retail_cents": 1499,
        "product_name": "Germany 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "germany-20gb-30",
        "country_code": "DE",
        "country_slug": "germany",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8179",
        "provider_slug": "zesimo-germany-20gb-30",
        "wholesale_cents": 1092,
        "retail_cents": 2599,
        "product_name": "Germany 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "france-1gb-7",
        "country_code": "FR",
        "country_slug": "france",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "182",
        "provider_slug": "zesimo-france-1gb-7",
        "wholesale_cents": 90,
        "retail_cents": 299,
        "product_name": "France 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "france-5gb-30",
        "country_code": "FR",
        "country_slug": "france",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1592",
        "provider_slug": "zesimo-france-5gb-30",
        "wholesale_cents": 378,
        "retail_cents": 899,
        "product_name": "France 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "france-10gb-30",
        "country_code": "FR",
        "country_slug": "france",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "12193",
        "provider_slug": "zesimo-france-10gb-30",
        "wholesale_cents": 616,
        "retail_cents": 1499,
        "product_name": "France 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "france-20gb-30",
        "country_code": "FR",
        "country_slug": "france",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "12195",
        "provider_slug": "zesimo-france-20gb-30",
        "wholesale_cents": 924,
        "retail_cents": 2199,
        "product_name": "France 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "japan-5gb-30",
        "country_code": "JP",
        "country_slug": "japan",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1779",
        "provider_slug": "zesimo-japan-5gb-30",
        "wholesale_cents": 378,
        "retail_cents": 899,
        "product_name": "Japan 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "japan-10gb-30",
        "country_code": "JP",
        "country_slug": "japan",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1780",
        "provider_slug": "zesimo-japan-10gb-30",
        "wholesale_cents": 658,
        "retail_cents": 1599,
        "product_name": "Japan 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "japan-20gb-30",
        "country_code": "JP",
        "country_slug": "japan",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "2145",
        "provider_slug": "zesimo-japan-20gb-30",
        "wholesale_cents": 1148,
        "retail_cents": 2699,
        "product_name": "Japan 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "thailand-5gb-30",
        "country_code": "TH",
        "country_slug": "thailand",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1531",
        "provider_slug": "zesimo-thailand-5gb-30",
        "wholesale_cents": 378,
        "retail_cents": 899,
        "product_name": "Thailand 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "thailand-10gb-30",
        "country_code": "TH",
        "country_slug": "thailand",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1757",
        "provider_slug": "zesimo-thailand-10gb-30",
        "wholesale_cents": 658,
        "retail_cents": 1599,
        "product_name": "Thailand 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "thailand-20gb-30",
        "country_code": "TH",
        "country_slug": "thailand",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8208",
        "provider_slug": "zesimo-thailand-20gb-30",
        "wholesale_cents": 1050,
        "retail_cents": 2499,
        "product_name": "Thailand 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "indonesia-5gb-30",
        "country_code": "ID",
        "country_slug": "indonesia",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1772",
        "provider_slug": "zesimo-indonesia-5gb-30",
        "wholesale_cents": 378,
        "retail_cents": 899,
        "product_name": "Indonesia 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "indonesia-10gb-30",
        "country_code": "ID",
        "country_slug": "indonesia",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1773",
        "provider_slug": "zesimo-indonesia-10gb-30",
        "wholesale_cents": 658,
        "retail_cents": 1599,
        "product_name": "Indonesia 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "indonesia-20gb-30",
        "country_code": "ID",
        "country_slug": "indonesia",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "9685",
        "provider_slug": "zesimo-indonesia-20gb-30",
        "wholesale_cents": 1050,
        "retail_cents": 2499,
        "product_name": "Indonesia 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "singapore-5gb-30",
        "country_code": "SG",
        "country_slug": "singapore",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1750",
        "provider_slug": "zesimo-singapore-5gb-30",
        "wholesale_cents": 337,
        "retail_cents": 799,
        "product_name": "Singapore 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "singapore-10gb-30",
        "country_code": "SG",
        "country_slug": "singapore",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "8394",
        "provider_slug": "zesimo-singapore-10gb-30",
        "wholesale_cents": 490,
        "retail_cents": 1199,
        "product_name": "Singapore 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "singapore-20gb-30",
        "country_code": "SG",
        "country_slug": "singapore",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8396",
        "provider_slug": "zesimo-singapore-20gb-30",
        "wholesale_cents": 868,
        "retail_cents": 2099,
        "product_name": "Singapore 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "south-korea-5gb-30",
        "country_code": "KR",
        "country_slug": "south-korea",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1785",
        "provider_slug": "zesimo-south-korea-5gb-30",
        "wholesale_cents": 378,
        "retail_cents": 899,
        "product_name": "South Korea 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "south-korea-10gb-30",
        "country_code": "KR",
        "country_slug": "south-korea",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1786",
        "provider_slug": "zesimo-south-korea-10gb-30",
        "wholesale_cents": 658,
        "retail_cents": 1599,
        "product_name": "South Korea 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "south-korea-20gb-30",
        "country_code": "KR",
        "country_slug": "south-korea",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "2146",
        "provider_slug": "zesimo-south-korea-20gb-30",
        "wholesale_cents": 1148,
        "retail_cents": 2699,
        "product_name": "South Korea 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "malaysia-5gb-30",
        "country_code": "MY",
        "country_slug": "malaysia",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "1739",
        "provider_slug": "zesimo-malaysia-5gb-30",
        "wholesale_cents": 378,
        "retail_cents": 899,
        "product_name": "Malaysia 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "malaysia-10gb-30",
        "country_code": "MY",
        "country_slug": "malaysia",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "1740",
        "provider_slug": "zesimo-malaysia-10gb-30",
        "wholesale_cents": 658,
        "retail_cents": 1599,
        "product_name": "Malaysia 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "malaysia-20gb-30",
        "country_code": "MY",
        "country_slug": "malaysia",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "2003",
        "provider_slug": "zesimo-malaysia-20gb-30",
        "wholesale_cents": 1148,
        "retail_cents": 2699,
        "product_name": "Malaysia 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "australia-1gb-7",
        "country_code": "AU",
        "country_slug": "australia",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "1620",
        "provider_slug": "zesimo-australia-1gb-7",
        "wholesale_cents": 98,
        "retail_cents": 299,
        "product_name": "Australia 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "australia-3gb-7",
        "country_code": "AU",
        "country_slug": "australia",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "33",
        "provider_slug": "zesimo-australia-3gb-7",
        "wholesale_cents": 347,
        "retail_cents": 899,
        "product_name": "Australia 3GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "australia-5gb-15",
        "country_code": "AU",
        "country_slug": "australia",
        "data_gb": 5.0,
        "validity_days": 15,
        "package_id": "34",
        "provider_slug": "zesimo-australia-5gb-15",
        "wholesale_cents": 550,
        "retail_cents": 1299,
        "product_name": "Australia 5GB 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "australia-10gb-30",
        "country_code": "AU",
        "country_slug": "australia",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "2006",
        "provider_slug": "zesimo-australia-10gb-30",
        "wholesale_cents": 658,
        "retail_cents": 1599,
        "product_name": "Australia 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "australia-20gb-30",
        "country_code": "AU",
        "country_slug": "australia",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "8572",
        "provider_slug": "zesimo-australia-20gb-30",
        "wholesale_cents": 1134,
        "retail_cents": 2699,
        "product_name": "Australia 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "as-1gb-7",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "11745",
        "provider_slug": "zesimo-as-1gb-7",
        "wholesale_cents": 210,
        "retail_cents": 499,
        "product_name": "Asia 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "as-3gb-30",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "11734",
        "provider_slug": "zesimo-as-3gb-30",
        "wholesale_cents": 322,
        "retail_cents": 799,
        "product_name": "Asia 3GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "eu-3gb-30",
        "country_code": None,
        "country_slug": "regional-europe",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "11705",
        "provider_slug": "zesimo-eu-3gb-30",
        "wholesale_cents": 420,
        "retail_cents": 999,
        "product_name": "Europe 3GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "gulf-1gb-7",
        "country_code": None,
        "country_slug": "regional-gulf",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "2546",
        "provider_slug": "zesimo-gulf-1gb-7",
        "wholesale_cents": 322,
        "retail_cents": 799,
        "product_name": "Gulf Region 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "gulf-3gb-30",
        "country_code": None,
        "country_slug": "regional-gulf",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "2545",
        "provider_slug": "zesimo-gulf-3gb-30",
        "wholesale_cents": 952,
        "retail_cents": 2299,
        "product_name": "Gulf Region 3GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "gulf-10gb-30",
        "country_code": None,
        "country_slug": "regional-gulf",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "2543",
        "provider_slug": "zesimo-gulf-10gb-30",
        "wholesale_cents": 3080,
        "retail_cents": 7299,
        "product_name": "Gulf Region 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "na-20gb-30",
        "country_code": None,
        "country_slug": "regional-north-america",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "588",
        "provider_slug": "zesimo-na-20gb-30",
        "wholesale_cents": 2476,
        "retail_cents": 5899,
        "product_name": "North America 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "la-1gb-7",
        "country_code": None,
        "country_slug": "regional-south-america",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "12090",
        "provider_slug": "zesimo-la-1gb-7",
        "wholesale_cents": 364,
        "retail_cents": 899,
        "product_name": "Latin America 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "sa-unlimited-3gb-3d",
        "country_code": "SA",
        "country_slug": "saudi-arabia",
        "data_gb": 3.0,
        "validity_days": 3,
        "package_id": "10899",
        "provider_slug": "zesimo-sa-unlimited-3d",
        "wholesale_cents": 1162,
        "retail_cents": 2499,
        "product_name": "Saudi Arabia Unlimited 3 Days",
    },
    {
        "phase": 5,
        "catalog_key": "sa-unlimited-3gb-5d",
        "country_code": "SA",
        "country_slug": "saudi-arabia",
        "data_gb": 3.0,
        "validity_days": 5,
        "package_id": "10901",
        "provider_slug": "zesimo-sa-unlimited-5d",
        "wholesale_cents": 1680,
        "retail_cents": 2999,
        "product_name": "Saudi Arabia Unlimited 5 Days",
    },
    {
        "phase": 5,
        "catalog_key": "sa-unlimited-3gb-15d",
        "country_code": "SA",
        "country_slug": "saudi-arabia",
        "data_gb": 3.0,
        "validity_days": 15,
        "package_id": "10907",
        "provider_slug": "zesimo-sa-unlimited-15d",
        "wholesale_cents": 5152,
        "retail_cents": 7999,
        "product_name": "Saudi Arabia Unlimited 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "sa-unlimited-3gb-30d",
        "country_code": "SA",
        "country_slug": "saudi-arabia",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "10909",
        "provider_slug": "zesimo-sa-unlimited-30d",
        "wholesale_cents": 7266,
        "retail_cents": 9999,
        "product_name": "Saudi Arabia Unlimited 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "as-unlimited-3d",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 3.0,
        "validity_days": 3,
        "package_id": "11759",
        "provider_slug": "zesimo-as-unlimited-3d",
        "wholesale_cents": 658,
        "retail_cents": 1599,
        "product_name": "Asia Unlimited 3 Days",
    },
    {
        "phase": 5,
        "catalog_key": "as-unlimited-5d",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 3.0,
        "validity_days": 5,
        "package_id": "11748",
        "provider_slug": "zesimo-as-unlimited-5d",
        "wholesale_cents": 924,
        "retail_cents": 2199,
        "product_name": "Asia Unlimited 5 Days",
    },
    {
        "phase": 5,
        "catalog_key": "as-unlimited-7d",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 3.0,
        "validity_days": 7,
        "package_id": "11750",
        "provider_slug": "zesimo-as-unlimited-7d",
        "wholesale_cents": 1162,
        "retail_cents": 2799,
        "product_name": "Asia Unlimited 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "as-unlimited-10d",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 3.0,
        "validity_days": 10,
        "package_id": "11752",
        "provider_slug": "zesimo-as-unlimited-10d",
        "wholesale_cents": 1386,
        "retail_cents": 3299,
        "product_name": "Asia Unlimited 10 Days",
    },
    {
        "phase": 5,
        "catalog_key": "as-unlimited-15d",
        "country_code": None,
        "country_slug": "regional-asia-pacific",
        "data_gb": 3.0,
        "validity_days": 15,
        "package_id": "11757",
        "provider_slug": "zesimo-as-unlimited-15d",
        "wholesale_cents": 2674,
        "retail_cents": 6299,
        "product_name": "Asia Unlimited 15 Days",
    },
    {
        "phase": 5,
        "catalog_key": "eu-uk-1gb-7",
        "country_code": None,
        "country_slug": "regional-eu-uk",
        "data_gb": 1.0,
        "validity_days": 7,
        "package_id": "11675",
        "provider_slug": "zesimo-eu-uk-1gb-7",
        "wholesale_cents": 182,
        "retail_cents": 499,
        "product_name": "European Union and United Kingdom 1GB 7 Days",
    },
    {
        "phase": 5,
        "catalog_key": "eu-uk-3gb-30",
        "country_code": None,
        "country_slug": "regional-eu-uk",
        "data_gb": 3.0,
        "validity_days": 30,
        "package_id": "11671",
        "provider_slug": "zesimo-eu-uk-3gb-30",
        "wholesale_cents": 252,
        "retail_cents": 599,
        "product_name": "European Union and United Kingdom 3GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "eu-uk-5gb-30",
        "country_code": None,
        "country_slug": "regional-eu-uk",
        "data_gb": 5.0,
        "validity_days": 30,
        "package_id": "11679",
        "provider_slug": "zesimo-eu-uk-5gb-30",
        "wholesale_cents": 336,
        "retail_cents": 799,
        "product_name": "European Union and United Kingdom 5GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "eu-uk-10gb-30",
        "country_code": None,
        "country_slug": "regional-eu-uk",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "11673",
        "provider_slug": "zesimo-eu-uk-10gb-30",
        "wholesale_cents": 504,
        "retail_cents": 1199,
        "product_name": "European Union and United Kingdom 10GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "eu-uk-20gb-30",
        "country_code": None,
        "country_slug": "regional-eu-uk",
        "data_gb": 20.0,
        "validity_days": 30,
        "package_id": "11681",
        "provider_slug": "zesimo-eu-uk-20gb-30",
        "wholesale_cents": 728,
        "retail_cents": 1799,
        "product_name": "European Union and United Kingdom 20GB 30 Days",
    },
    {
        "phase": 5,
        "catalog_key": "gl-lite-10gb-30",
        "country_code": None,
        "country_slug": "regional-global-lite",
        "data_gb": 10.0,
        "validity_days": 30,
        "package_id": "7910",
        "provider_slug": "zesimo-gl-lite-10gb-30",
        "wholesale_cents": 1612,
        "retail_cents": 3799,
        "product_name": "Global Lite 10GB 30 Days",
    },
]


def by_phase(phase: int) -> List[Dict[str, Any]]:
    return [row for row in ZESIMO_SKU_MAP if row["phase"] == phase]


def get_sku(catalog_key: str) -> Optional[Dict[str, Any]]:
    for row in ZESIMO_SKU_MAP:
        if row["catalog_key"] == catalog_key:
            return row
    return None


def fulfillment_rows() -> List[Dict[str, Any]]:
    """Rows ready for plan_fulfillment_map upsert."""
    rows: List[Dict[str, Any]] = []
    for sku in ZESIMO_SKU_MAP:
        package_id = sku.get("package_id")
        if not package_id:
            raise ValueError(f"Missing package_id for {sku['catalog_key']}")
        rows.append(
            {
                "catalog_key": sku["catalog_key"],
                "country_code": sku.get("country_code"),
                "country_slug": sku.get("country_slug"),
                "data_gb": sku.get("data_gb"),
                "validity_days": sku.get("validity_days"),
                "provider": "zesimo",
                "provider_sku": str(package_id),
                "provider_slug": sku["provider_slug"],
                "wholesale_cents": sku["wholesale_cents"],
                "period_num": None,
                "notes": f"Zesimo phase {sku['phase']}: {sku['product_name']}",
                "is_active": True,
                "admin_approved": True,
            }
        )
    return rows


assert len(ZESIMO_SKU_MAP) == 142
assert len(by_phase(1)) == 4
assert len(by_phase(2)) == 11
assert len(by_phase(3)) == 9
assert len(by_phase(4)) == 6
assert len(by_phase(5)) == 112
assert all(row.get("package_id") for row in ZESIMO_SKU_MAP)
assert len({row["catalog_key"] for row in ZESIMO_SKU_MAP}) == len(ZESIMO_SKU_MAP)
